version: '3.3'

services:
  pg-db:
    image: postgres
    restart: always
    container_name: db_etl
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  etl:
    image: etl_demo
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      PYTHONUNBUFFERED: 1
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db_etl
      POSTGRES_PORT: 5432

    depends_on:
      - pg-db
    container_name: etl_1
    ports:
      - 5000:5000
    # entrypoint: /bin/sh
    # entrypoint: ["sh", "-c", "sleep 2073600"]

